---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2


provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info
  require_chef_omnibus: 12.18.31

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[alfresco-utils::package-repositories]
      - recipe[alfresco-transformations::default]
    attributes: {
      "transformations": {
        "libreoffice" : {
            "initialise": {
                "enabled" : true
              }
            }
          }
        }

  - name: extras
    run_list:
      - recipe[alfresco-utils::package-repositories]
      - recipe[alfresco-transformations::default]
    attributes: {
      "transformations": {
            "install_fonts" : true,
            "install_swftools" : true,
            "imagemagick": {
                "use_im_os_repo" : true
              }
            }
          }
